apiVersion: v1
kind: Service
metadata:
  name: laravel-mysql
  labels:
    app: laravel-application
spec:
  ports:
    - port: 3306
  selector:
    app: laravel-application
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: laravel-application
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: laravel-mysql
  labels:
    app: laravel-application
spec:
  selector:
    matchLabels:
      app: laravel-application
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: laravel-application
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
