apiVersion: v1
kind: Secret
metadata:
  name: laravel-app-secret
type: Opaque
data:
  .env: QVBQX05BTUU9TGFyYXZlbApBUFBfRU5WPWxvY2FsCkFQUF9LRVk9YmFzZTY0Ok1sMis3VlNweVZ4bnB4N1kxRE5wSDQreldvL3ZvSHhqOUloWFkvaWc4aXM9CkFQUF9ERUJVRz10cnVlCkFQUF9MT0dfTEVWRUw9ZGVidWcKCkRCX0NPTk5FQ1RJT049bXlzcWwKREJfSE9TVD1teXNxbC1xdWVzdC1wb2QuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbApEQl9QT1JUPTMzMDYKREJfREFUQUJBU0U9bGFyYXZlbApEQl9VU0VSTkFNRT1yb290CkRCX1BBU1NXT1JEPQoKQlJPQURDQVNUX0RSSVZFUj1sb2cKQ0FDSEVfRFJJVkVSPWZpbGUKU0VTU0lPTl9EUklWRVI9ZmlsZQpRVUVVRV9EUklWRVI9c3luYwoKUkVESVNfSE9TVD0xMjcuMC4wLjEKUkVESVNfUEFTU1dPUkQ9bnVsbApSRURJU19QT1JUPTYzNzkKCk1BSUxfRFJJVkVSPXNtdHAKTUFJTF9IT1NUPXNtdHAubWFpbHRyYXAuaW8KTUFJTF9QT1JUPTI1MjUKTUFJTF9VU0VSTkFNRT1udWxsCk1BSUxfUEFTU1dPUkQ9bnVsbApNQUlMX0VOQ1JZUFRJT049bnVsbAoKUFVTSEVSX0FQUF9JRD0KUFVTSEVSX0FQUF9LRVk9ClBVU0hFUl9BUFBfU0VDUkVUPQpCQUNLVVBfREFUQV9QQVRIPX4vLmJhY2t1cHMvbGFyYXZlbAo=
